<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <OutputType>WinExe</OutputType>
    <RootNamespace>BTSS.IAR</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WindowsPackageType>None</WindowsPackageType>
    <CreateMSIXPackage>False</CreateMSIXPackage>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <ApplicationTitle>BTSS.IAR</ApplicationTitle>
    <ApplicationId>com.companyname.btss.iar</ApplicationId>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
  </PropertyGroup>

  <ItemGroup>
    <MauiFont Include="Resources\Fonts\*" />
    <MauiAsset Include="wwwroot\**" LogicalName="wwwroot\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.50" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.4" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.50" />
    <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.50" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BTSS.IAR.Record\BTSS.IAR.Record.csproj" />
  </ItemGroup>
</Project>
